// var responseList = ["Old People Smell", "Judge Judy", "Hot Pockets",  "The Trail of Tears", "An M. Night Shyamalan plot twist", "Robert Downey, Jr.", "Magnets", "Mr. Clean right behing you", "Natalie Portman", "The Care Bear Stare", "Jobs", "Sarah Palin", "Being Fabulous", "The World of Warcraft", "Dick Cheney", "The Amish", "Peeing a little bit", "Pooping Back and forth. Forever", "Prancing", "My relationship status", "Over compensation", "Court-ordered rehab", "Being on fire", "Old-people smell", "Skeletor", "The light of a billion suns", "A good sniff", "One trillion dollars", "Silence", "Dying", "Growing a pair", "Justin Bieber", "Balls", "The invisible hand", "Powerful thighs", "Crippling debt", "Teaching a robot to love", "Michael Jackson", "Horse Meat", "A really cool hat", "My soul", "Shapeshifters", "A sausage festival", "RoboCop", "Fiery poops", "White-man scalps", "Joe Biden", "Lockjaw", "Hip hop jewels", "Grave robbing", "A monkey smoking a cigar", "The Great Depression", "A foul mouth", "When you fart and a little bit comes out", "Vigorous jazz hands", "New age music", "Kanye West", "The American Dream", "A spastic nerd", "Sweet, sweet vengeance", "Authentic Mexican cuising", "Preteens", "Land mines", "Me time", "The South", "Opposable thumbs", "Inapproapriate yodeling", "Exactly what you'd expect", "A time travel paradox", "AXE Body Spray", "An oversized lollipop", "A tiny horse", "Boogers", "My humps", "Darth Vader", "Figgy pudding", "Free Samples", "A bag of magic beans", "Prancing", "Magnets", "A can of whoop-ass", "Vikings", "The Kook-Aid Man", "Hot cheese", "Nicolas Cage", "Lunchables", "Yeast", "Lady Gaga", "Republicans", "A sea of troubles", "Giving 110%", "Puppies!", "Soup that is too hot", "The Big Bang", "Switching to Geico", "Christopher Walken", "Aaron Burr", "The Hamburglar", "Hot people", "The Hustle", "The glass celing", "Miley Cyrus at 55"];

INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Old People Smell", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Judge Judy", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Hot Pockets", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Trail of Tears", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("An M. Night Shyamalan plot twist", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Robert Downey, Jr.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Magnets", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Mr. Clean right behing you", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Natalie Portman", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Care Bear Stare", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Jobs", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Sarah Palin", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Being Fabulous", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The World of Warcraft", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Dick Cheney", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Amish", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Peeing a little bit", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Pooping Back and forth. Forever", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Prancing", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("My relationship status", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Over compensation", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Court-ordered rehab", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Being on fire", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Old-people smell", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Skeletor", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The light of a billion suns", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A good sniff", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("One trillion dollars", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Silence", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Dying", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Growing a pair", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Justin Bieber", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Balls", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The invisible hand", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Powerful thighs", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Crippling debt", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Teaching a robot to love", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Michael Jackson", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Horse Meat", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A really cool hat", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("My soul", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Shapeshifters", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A sausage festival", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("RoboCop", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Fiery poops", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("White-man scalps", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Joe Biden", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Lockjaw", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Hip hop jewels", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Grave robbing", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A monkey smoking a cigar", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Great Depression", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A foul mouth", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("When you fart and a little bit comes out", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Vigorous jazz hands", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("New age music", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Kanye West", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The American Dream", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A spastic nerd", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Sweet, sweet vengeance", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Authentic Mexican cuising", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Preteens", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Land mines", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Me time", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The South", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Opposable thumbs", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Inapproapriate yodeling", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Exactly what you'd expect", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A time travel paradox", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("AXE Body Spray", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("An oversized lollipop", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A tiny horse,", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Boogers", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("My humps", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("My humps", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Darth Vader", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Figgy pudding", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Free Samples", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A bag of magic beans", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Prancing", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Magnets", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A can of whoop-ass", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Vikings", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Kook-Aid Man", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Hot cheese", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Nicolas Cage", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Lunchables", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Yeast", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Lady Gaga", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Republicans", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A sea of troubles", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Giving 110%", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Puppies!", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Soup that is too hot", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Big Bang", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Switching to Geico", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Christopher Walken", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Aaron Burr", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Hamburglar", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Hot people", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Hustle", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The glass celing", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Miley Cyrus at 55", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());