INSERT INTO response_cards (description, createdAt, updatedAt) VALUES ("Old People Smell", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO response_cards (description, createdAt, updatedAt) VALUES ("Judge Judy", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO response_cards (description, createdAt, updatedAt) VALUES ("Hot Pockets", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Trail of Tears", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("An M. Night Shyamalan plot twist", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Robert Downey, Jr.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Magnets", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Mr. Clean right behing you", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Natalie Portman", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Care Bear Stare", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Jobs", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Sarah Palin", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Being Fabulous", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The World of Warcraft", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Dick Cheney", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Amish", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Peeing a little bit", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Pooping Back and forth. Forever", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Prancing", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("My relationship status", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Over compensation", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Court-ordered rehab", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Being on fire", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Old-people smell", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Skeletor", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The light of a billion suns", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A good sniff", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("One trillion dollars", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Silence", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Dying", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Growing a pair", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Justin Bieber", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Balls", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The invisible hand", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Powerful thighs", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Crippling debt", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Teaching a robot to love", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Michael Jackson", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Horse Meat", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A really cool hat", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("My soul", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Shapeshifters", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A sausage festival", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("RoboCop", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Fiery poops", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("White-man scalps", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Joe Biden", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Lockjaw", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Hip hop jewels", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Grave robbing", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A monkey smoking a cigar", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Great Depression", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A foul mouth", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("When you fart and a little bit comes out", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Vigorous jazz hands", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("New age music", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Kanye West", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The American Dream", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A spastic nerd", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Sweet, sweet vengeance", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Authentic Mexican cuising", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Preteens", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Land mines", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Me time", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The South", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Opposable thumbs", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Inapproapriate yodeling", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Exactly what you'd expect", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A time travel paradox", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("AXE Body Spray", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("An oversized lollipop", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A tiny horse,", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Boogers", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("My humps", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("My humps", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Darth Vader", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Figgy pudding", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Free Samples", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A bag of magic beans", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Prancing", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Magnets", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A can of whoop-ass", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Vikings", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Kook-Aid Man", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Hot cheese", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Nicolas Cage", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Lunchables", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Yeast", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Lady Gaga", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Republicans", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("A sea of troubles", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Giving 110%", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Puppies!", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Soup that is too hot", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Big Bang", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Switching to Geico", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Christopher Walken", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Aaron Burr", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Hamburglar", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Hot people", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The Hustle", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("The glass celing", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.response_cards (description, createdAt, updatedAt) VALUES ("Miley Cyrus at 55", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());


INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What's that smell?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("I got 99 problems but _____ ain't one.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("Maybe she's born with it. Maybe it's ____.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What's my next Happy Meal Toy?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("Here is the church. Here is the steepple. Open the doors and theres___.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("___. Thats how I want to die.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("Today on Maury: 'Help! My son is ___!'", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What ended my last relationship?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("Whats a girl's best friend?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("Whats Batman's guilty pleasure?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What's the most emo?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("I get by with a little help from my ___.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("Instead of coal, Santa now gives the bad children ___.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("White people like ___.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What are my parents hiding from me?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What will I bring back in time to convince people I am a powerful wizard?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("How am I maintaing my relationship status?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("Next on ESPN2, the World Series of ___.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What gives me uncontrollable gas?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What's my secret power?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What's there a ton of in heaven?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What would grandma find disturbing, yet oddly charming?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What helps Obama unwind?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("Why am I sticky?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What gets better with age?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("Daddy, why is mommy crying?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("Why do I hurt all over?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What I giving up for Lent?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("The Smithsonian Museum of Natural History has just opened an interactive exhibit on ___.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("When I am President of the United States, I will create a Department of ___.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("When I am a billionaire, I shall erect a 50-foot statue to commemorate ___.", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("Whats the new fadd diet?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO project2.question_cards (description, createdAt, updatedAt) VALUES ("What never fails to liven up the party?", CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());